login-register-logout feature
Linhnef/todo-list pull request #1
Opened 2021-07-14 09:33 UTC by Linhnef

2021-07-14 10:12 UTC, hoaikthai requested changes

2021-07-14 10:12 UTC, hoaikthai commented on src/components/Default.tsx
> +import * as React from "react"
e có thể dùng Dialog của MaterialUI, ko cần implement

2021-07-14 10:12 UTC, hoaikthai commented on src/layouts/MainLayout.tsx
> +      api.defaults.headers.common["Authorization"] = `Bearer ${token}`;
dùng interceptor của axios, ko xử lý ở đây

2021-07-14 10:12 UTC, hoaikthai commented on src/pages/LoginPage.tsx
> +import { useHistory } from "react-router-dom";
rename file thành Login, nó đã ở trong folder pages nên mặc nhiên là page rồi

2021-07-14 10:12 UTC, hoaikthai commented on src/pages/LoginPage.tsx
> +export const LoginPage = () => {
```suggestion
export const Login = () => {
```

2021-07-14 10:12 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +type registerRequest = {
```suggestion
type RegisterRequest = {
```

2021-07-14 10:12 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +type logoutResponse = {
```suggestion
type LogoutResponse = {
```

2021-07-14 10:12 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +type profileResponse = {
tại sao e ko dùng type User ở src/services/api/types/User.ts thay vì phải tạo?

2021-07-14 10:12 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +const profile = (api: AxiosInstance) => async (): Promise<User | undefined> => {
```suggestion
const getCurrentUser = (api: AxiosInstance) => async (): Promise<User | undefined> => {
```

2021-07-14 10:12 UTC, hoaikthai commented on src/pages/HomePage.tsx
> +import { NavLink } from "react-router-dom";
rename thành Home

2021-07-14 10:12 UTC, hoaikthai commented on src/index.tsx
>  import './index.css';
format file

2021-07-14 10:12 UTC, hoaikthai commented on src/hooks/useInput.ts
> +import * as React from 'react'
format file

2021-07-14 10:12 UTC, hoaikthai commented on src/hooks/useInput.ts
> +export const useInput =  (validateValue : (arg : string) => boolean) => {
`(arg : string) => boolean` là 1 function mà tại sao lại đặt tên là value?

2021-07-14 10:12 UTC, hoaikthai commented on src/App.tsx
> +/* const HomeLazy = React.lazy(() => import('./pages/Home/HomePage')
bỏ

2021-07-14 10:12 UTC, hoaikthai commented on src/App.tsx
> +      <Route path="/profile" component={ProfilePage}></Route>
chưa login thì e vẫn vào page này đc à

2021-07-14 10:12 UTC, hoaikthai commented on src/components/Login.tsx
> +import styled from "styled-components";
e có thể dùng component này ở chỗ nào khác ngoài page Login ko? Nếu ko thì tạo component như này có cần thiết ko? Tương tự cho Register, Update, ....

2021-07-14 10:12 UTC, hoaikthai commented on src/components/Profile.tsx
> +import { Grid } from '@material-ui/core';
format file

2021-07-14 10:12 UTC, hoaikthai commented on src/components/Register.tsx
> +  /*    const handleLogin= (event : any) => {
bỏ

2021-07-14 10:12 UTC, hoaikthai commented on src/components/Update.tsx
> +const user = {
bỏ

2021-07-14 10:12 UTC, hoaikthai commented on src/components/Update.tsx
> +      <ListItem style={{ marginLeft: 45 }}>
sao ko chỉnh = styled-component?

2021-07-14 10:12 UTC, hoaikthai commented on src/components/Update.tsx
> +            <Button variant="outlined">UPDATE</Button>
e dùng variant này nhiều như vậy thì có thể tạo 1 component ButtonOutlined

2021-07-14 10:12 UTC, hoaikthai commented on src/components/UploadImage.tsx
> +    console.log(e.target.files)
bỏ

2021-07-14 10:12 UTC, hoaikthai commented on src/contexts/authenticationContext.tsx
> +let logOutTime : ReturnType<typeof setTimeout>;
ko dùng thì bỏ

2021-07-14 10:12 UTC, hoaikthai commented on src/contexts/authenticationContext.tsx
> +import * as React from 'react';
format file

2021-07-14 10:12 UTC, hoaikthai commented on src/contexts/authenticationContext.tsx
> +export const AuthenticationContext = React.createContext<contextProps>({
context sẽ có
- user
- hàm login -> dùng useAsync hook gọi api login
- hàm register -> dùng useAsync hook gọi api register
- hàm logout -> dùng useAsync hook gọi api logout

2021-07-15 02:29 UTC, Linhnef commented on src/contexts/authenticationContext.tsx
> +export const AuthenticationContext = React.createContext<contextProps>({
anh ơi cái này làm sao để pass dynamic value vào useAsync khi không được sử dụng trong hàm ạ.
const useLogin = (loginRequest: LoginRequest) =>
  UseAsync<string | undefined>(() => UseAppApiClient().login(loginRequest), true);

2021-07-15 03:02 UTC, hoaikthai requested changes

2021-07-15 03:02 UTC, hoaikthai commented on src/components/RegisterForm.tsx
> +            style={emailInputHasError ? { backgroundColor: "violet" } : { backgroundColor: "white" }}
dùng TextField của MaterialUI, nó có 1 prop error để truyền boolean để đổi style
có đổi style thì dùng styled-component, ko truyền như này

2021-07-15 03:02 UTC, hoaikthai commented on src/components/RegisterForm.tsx
> +import styled from "styled-components"
tại sao e phải tạo component cho RegisterForm, nó có đc dùng ở đâu khác ngoài page Register ko?

2021-07-15 03:02 UTC, hoaikthai commented on src/contexts/authenticationContext.tsx
> +let logOutTime : ReturnType<typeof setTimeout>;
@Linhnef e chưa fix tại sao lại resolve?

2021-07-15 03:02 UTC, hoaikthai commented on src/contexts/authenticationContext.tsx
> +  children : any
```suggestion
  children : ReactNode
```

2021-07-15 03:02 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +const setToken =
dùng axios interceptor chứ ko phải tạo hàm như này e
https://github.com/axios/axios#interceptors

2021-07-15 03:02 UTC, hoaikthai commented on src/components/UserProfileCard.tsx
> +const ProfileTitle = styled(Grid)`
để styled-components xuống dưới cùng

2021-07-15 03:02 UTC, hoaikthai commented on src/components/UserProfileCard.tsx
> +interface profileProps {
```suggestion
interface ProfileProps {
```
type nên kiểu PascalCase, camelCase dành cho biến và hàm

2021-07-15 03:21 UTC, hoaikthai requested changes

2021-07-15 03:21 UTC, hoaikthai commented on src/App.tsx
> +      <Route exact path="/">
```suggestion
      { isLoggedIn && (
          <>
              // Private routes
          </>
      ) }
```

2021-07-15 03:21 UTC, hoaikthai commented on src/components/ButtonOutlined.tsx
> +import { ListItem, TextField, ListItemSecondaryAction, IconButton, Button } from "@material-ui/core"
ý a nói ButtonOutlined là mỗi cái `<Button variant="outlined">UPDATE</Button>` thôi, e cho 1 component làm nhiều việc thế này thì khó reuse

2021-07-15 03:21 UTC, hoaikthai commented on src/App.tsx
> -import React from 'react';
format file

2021-07-15 03:21 UTC, hoaikthai commented on src/components/Default.tsx
> +import * as React from "react"
chưa bỏ tại sao resolve?

2021-07-15 03:21 UTC, hoaikthai commented on src/components/LoginForm.tsx
> +interface formProps {
```suggestion
interface FormProps {
```

2021-07-15 03:21 UTC, hoaikthai commented on src/components/LoginForm.tsx
> +  let formValid = false
tính toán form valid hay chưa bằng 1 hàm riêng, ko dùng biến let

2021-07-15 03:21 UTC, hoaikthai commented on src/components/RegisterForm.tsx
> +import styled from "styled-components"
ko thì đống này có thể bỏ hết ra ngoài Register page, tương tự với Login, Update,...

2021-07-15 03:21 UTC, hoaikthai commented on src/components/RegisterForm.tsx
> +  let formValid = false
tính toán form valid hay chưa bằng 1 hàm riêng, ko dùng biến let

2021-07-15 03:21 UTC, hoaikthai commented on src/components/UpdateUserInformationCard.tsx
> +  const nameChange = (event : any) =>{
có cách nào đỡ lặp code như này ko?

2021-07-15 03:21 UTC, hoaikthai commented on src/components/UploadAvatarUserCard.tsx
> +    console.log(e.target.files)
bỏ

2021-07-15 03:21 UTC, hoaikthai commented on src/components/UploadAvatarUserCard.tsx
> +interface uploadProps {
```suggestion
interface UploadProps {
```

2021-07-15 03:21 UTC, hoaikthai commented on src/components/UploadAvatarUserCard.tsx
> +  upload: (img: FormData) => void
FormData tại sao đặt tên là img?

2021-07-15 03:21 UTC, hoaikthai commented on src/hooks/useAppApiClient.ts
> -import { getAppContainer } from "../container"
format file

2021-07-15 03:21 UTC, hoaikthai commented on src/contexts/authenticationContext.tsx
> +import * as React from 'react';
chưa fix tại sao resolve?

2021-07-15 03:21 UTC, hoaikthai commented on src/components/BackgroundCard.tsx
> +import * as React from "react"
e có Modal của MaterialUI rồi, tại sao cần cái này?

2021-07-15 03:21 UTC, hoaikthai commented on src/components/LogoutButton.tsx
> +    <Button onClick={props.logout} variant="contained" color="secondary">
tạo component ButtonSecondary để trong src/components/buttons

2021-07-15 03:21 UTC, hoaikthai commented on src/components/ButtonOutlined.tsx
> +import { ListItem, TextField, ListItemSecondaryAction, IconButton, Button } from "@material-ui/core"
để trong src/components/buttons

2021-07-15 03:21 UTC, hoaikthai commented on src/components/UpdateUserInformationCard.tsx
> +interface updateProps {
```suggestion
interface UpdateProps {
```

2021-07-15 03:21 UTC, hoaikthai commented on src/components/UpdateUserInformationCard.tsx
> +  const nameChange = (event: any) => {
có cách nào đỡ lặp code ko?
define type any làm gì?

2021-07-15 03:21 UTC, hoaikthai commented on src/hooks/useAsync.ts
> +//const action = useAsync<T>(() => Promise<T>));
bỏ

2021-07-15 03:21 UTC, hoaikthai commented on src/hooks/useConfig.ts
> -import { getAppContainer } from "../container"
format file

2021-07-15 03:21 UTC, hoaikthai commented on src/layouts/MainLayout.tsx
> +interface layoutProps {
```suggestion
interface MainLayoutProps {
```

2021-07-15 03:21 UTC, hoaikthai commented on src/layouts/MainLayout.tsx
> +      console.log(response);
bỏ hết console.log

2021-07-15 03:21 UTC, hoaikthai commented on src/layouts/MainLayout.tsx
> +import * as React from "react";
bỏ

2021-07-16 07:54 UTC, hoaikthai requested changes

2021-07-16 07:54 UTC, hoaikthai commented on src/components/DialogCard.tsx
> +  width: 50%;
e có chắc là cái Dialog nào cũng width 50% ko? Nếu chỉ có 1 chỗ thì khỏi tạo riêng component mà custom thôi

2021-07-16 07:54 UTC, hoaikthai commented on src/pages/Register.tsx
> +    handleSignUp(name, email, password, parseInt(age + ""))
+"" để làm gì e?

2021-07-16 07:54 UTC, hoaikthai commented on src/pages/Login.tsx
> +import { useHistory } from "react-router-dom"
format file

2021-07-16 07:54 UTC, hoaikthai commented on src/pages/Login.tsx
> +const FormModal = styled(Modal)`
styled component bỏ cuối

2021-07-16 07:54 UTC, hoaikthai commented on src/pages/Home.tsx
> +  const { isLogin, user, getCurrentUser } = React.useContext(AuthenticationContext)
```suggestion
  const { isLogin, user, getCurrentUser } = useContext(AuthenticationContext)
```

2021-07-16 07:54 UTC, hoaikthai commented on src/pages/Home.tsx
> +const ProfileGrid = styled(Grid)`
styled component để cuối

2021-07-16 07:54 UTC, hoaikthai commented on src/pages/Home.tsx
> +  const [name, setName] = React.useState<string | undefined>()
```suggestion
  const [name, setName] = useState("")
```

2021-07-16 07:54 UTC, hoaikthai commented on src/pages/Home.tsx
> +import { TextField,Grid,ListItem,ListItemSecondaryAction,IconButton } from "@material-ui/core"
trang Home ko phải để Update user info

2021-07-16 07:54 UTC, hoaikthai commented on src/layouts/MainLayout.tsx
> +      <LogoutButton logout={handleLogout}></LogoutButton>
page nào cũng có logout button á?
thường ni nó ở trên navbar

2021-07-16 07:54 UTC, hoaikthai commented on src/components/buttons/ButtonOutlined.tsx
> +import { Button } from "@material-ui/core"
format file

2021-07-19 00:49 UTC, hoaikthai requested changes

2021-07-19 00:49 UTC, hoaikthai commented on src/components/buttons/ButtonOutlined.tsx
> +export const ButtonOutlined = (props: ButtonOutlinedProps) => {
e làm như này thì mỗi khi dùng props khác của Material Button thì lại phải khai thêm trong ButtonOutlinedProps
=> mỗi lần thêm prop mới lại phải sửa
```suggestion
export const ButtonOutlined = styled(Button).attrs((props) => ({ variant: "outlined", ...props }))``
```
như này thì mình có thể dùng component như Button của Material UI

2021-07-19 00:49 UTC, hoaikthai commented on src/components/buttons/ButtonSecondary.tsx
> +import { Button } from "@material-ui/core"
tương tự ButtonOutlined

2021-07-19 00:49 UTC, hoaikthai commented on src/contexts/authenticationContext.tsx
> +export const AuthenticationContext = React.createContext<ContextProps>({
sorry e, giờ mình sửa lại AuthContext chỉ gồm có
user, setUser, token
việc xử lý login, register, ... sẽ xử lý ở page

2021-07-19 00:49 UTC, hoaikthai commented on src/components/Header.tsx
> +const RightGrid = styled(Grid)`
RIghtGrid là sao e?

2021-07-19 00:49 UTC, hoaikthai commented on src/hooks/useAppApiClient.ts
> -import { getAppContainer } from "../container"
@Linhnef format rồi sao có ; vậy?

2021-07-19 00:49 UTC, hoaikthai commented on src/hooks/useConfig.ts
> -import { getAppContainer } from "../container"
@Linhnef format rồi sao còn ; ?

2021-07-19 00:49 UTC, hoaikthai commented on src/hooks/useInput.ts
> +import * as React from 'react'
@Linhnef chưa format

2021-07-19 00:49 UTC, hoaikthai commented on src/index.tsx
>  import './index.css';
@Linhnef chưa format

2021-07-19 00:49 UTC, hoaikthai commented on src/layouts/EmptyLayout.tsx
> +  children: React.ReactNode
```suggestion
  children: ReactNode
```
dùng hàm nào thì import hàm đấy thôi, khỏi phải import nguyên cả React

2021-07-19 00:49 UTC, hoaikthai commented on src/layouts/EmptyLayout.tsx
> +      <Header></Header>
EmptyLayout cần header làm gì?

2021-07-19 00:49 UTC, hoaikthai commented on src/layouts/MainLayout.tsx
> +  children: React.ReactNode
```suggestion
  children: ReactNode
```

2021-07-19 00:49 UTC, hoaikthai commented on src/pages/Home.tsx
> +        {user !== undefined ? (
chưa login thì bị redirect qua page login rồi, sao phải handle ở đây nhỉ?

2021-07-19 00:49 UTC, hoaikthai commented on src/pages/Login.tsx
> +const FormModal = styled(Modal)`
sao lại bấm resolve? @Linhnef

2021-07-19 00:49 UTC, hoaikthai commented on src/pages/Register.tsx
> +export const Form = styled.form`
styled component bỏ cuối

2021-07-19 00:49 UTC, hoaikthai commented on src/pages/Register.tsx
> +export const FormButton = styled.button`
dùng component Button của Material UI
còn không e tự đặt tên và tạo component trong src/components/buttons

2021-07-19 00:49 UTC, hoaikthai commented on src/pages/UpdateUser.tsx
> +  const emailChange = (event: any) => {
có cách nào tránh lặp code như này ko ?

2021-07-19 00:49 UTC, hoaikthai commented on src/pages/UpdateUser.tsx
> +      {user ? (
chưa login thì đã bị redirect qua login, ko handle việc login hay chưa ở đây

2021-07-19 00:49 UTC, hoaikthai commented on src/services/api/createApiClient.ts
>  import axios, { AxiosInstance } from "axios"
format file

2021-07-19 00:49 UTC, hoaikthai commented on src/services/api/createApiClient.ts
> +    let token = getLocalToken();
```suggestion
    const token = getLocalToken();
```

2021-07-19 00:49 UTC, hoaikthai commented on src/services/api/createApiClient.ts
> +      error.config.headers['Authorization'] =`Bearer ${token}`;
e set cho response khi bị 401 để làm gì?

2021-07-19 00:49 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +      return res.data.token
ko trả user để setUser cho context à e?

2021-07-19 00:49 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +      return res.data.token
ko trả user để setUser cho context à e?

2021-07-19 05:34 UTC, Linhnef commented on src/pages/Register.tsx
> +export const Form = styled.form`
em tưởng nhầm là import styled from "styled-components" bỏ cuối @hoaikthai

2021-07-19 07:08 UTC, hoaikthai requested changes

2021-07-19 07:08 UTC, hoaikthai commented on src/components/inputs/InputOutlined.tsx
> +  width: 90%;
a ko nghĩ là width vs height lúc nào cũng như vậy đâu, mấy cái này có thể custom ở component/page nào dùng

2021-07-19 07:08 UTC, hoaikthai commented on src/contexts/authenticationContext.tsx
> +  user: initialUser,
```suggestion
  user: null,
```

2021-07-19 07:08 UTC, hoaikthai commented on src/contexts/authenticationContext.tsx
> +  const tokenData = retrieveStoredToken()
```suggestion
  const tokenData = localStorage.getItem("token")
   const [token, setToken] = useState<string | undefined | null>(initialToken)
```

2021-07-19 07:08 UTC, hoaikthai commented on src/contexts/authenticationContext.tsx
> +const retrieveStoredToken = () => {
bỏ

2021-07-19 07:08 UTC, hoaikthai commented on src/contexts/authenticationContext.tsx
> +export const AuthenticationContextProvider = (props: autheChildren) => {
```suggestion
export const AuthenticationContextProvider = (props: AuthenticationContextProviderProps) => {
```

2021-07-19 07:08 UTC, hoaikthai commented on src/contexts/authenticationContext.tsx
> +  children: any
```suggestion
  children: ReactNode
```

2021-07-19 07:08 UTC, hoaikthai commented on src/contexts/authenticationContext.tsx
> +interface autheChildren {
```suggestion
interface AuthenticationContextProviderProps {
```

2021-07-19 07:08 UTC, hoaikthai commented on src/contexts/authenticationContext.tsx
> +    setUser: handleSetUser,
```suggestion
    setUser,
    setToken
```

2021-07-19 07:08 UTC, hoaikthai commented on src/contexts/authenticationContext.tsx
> +  const handleSetUser = (data: User) => {
bỏ

2021-07-19 07:08 UTC, hoaikthai commented on src/contexts/authenticationContext.tsx
> +  const handleSetToken = (data: string | undefined | null) => {
bỏ

2021-07-19 07:08 UTC, hoaikthai commented on src/pages/Home.tsx
> +    const { data, error } = useLogout
e định page nào cũng handle việc logout như này á?

2021-07-19 07:08 UTC, hoaikthai commented on src/hooks/useAsync.ts
> +const UseAsync = <T, TData>(asyncFunction: (...data: TData[]) => Promise<T>, active: boolean = false) => {
```suggestion
const useAsync = <T, TData>(asyncFunction: (...data: TData[]) => Promise<T>, active: boolean = false) => {
```

2021-07-19 07:08 UTC, hoaikthai commented on src/hooks/useAppApiClient.ts
> +export const UseAppApiClient = () => getAppContainer().apiClient
```suggestion
export const useAppApiClient = () => getAppContainer().apiClient
```

2021-07-19 07:08 UTC, hoaikthai commented on src/pages/Login.tsx
> +  const useLogin = UseAsync<LoginResponse | undefined, LoginRequest>(api.login)
```suggestion
  const login = UseAsync<LoginResponse | undefined, LoginRequest>(api.login)
```

2021-07-19 07:08 UTC, hoaikthai commented on src/pages/Login.tsx
> +  const [loading, setLoading] = useState<boolean>(false)
bỏ

2021-07-19 07:08 UTC, hoaikthai commented on src/pages/Login.tsx
> +  const [error, setError] = useState<any>(null)
bỏ

2021-07-19 07:08 UTC, hoaikthai commented on src/pages/Login.tsx
> +  useEffect(() => {
bỏ

2021-07-19 07:08 UTC, hoaikthai commented on src/hooks/useAsync.ts
> +  const fetch = useCallback(async (...data: TData[]) => {
```suggestion
  const run = useCallback(async (...data: TData[]) => {
```

2021-07-19 07:08 UTC, hoaikthai commented on src/pages/Login.tsx
> +    useLogin.fetch({ email: email, password: password })
```suggestion
    const result = login.run({ email: email, password: password })
    if (!result) return
    
    setToken(data.token)
    setUser(data.user)
```

2021-07-19 07:08 UTC, hoaikthai commented on src/pages/Login.tsx
> +      {!(error === null) ? (
```suggestion
      {!(login.error === null) ? (
```

2021-07-19 07:08 UTC, hoaikthai commented on src/pages/Register.tsx
> +import { useContext, useState, useEffect } from "react"
tương tự page Login

2021-07-19 07:08 UTC, hoaikthai commented on src/pages/UpdateUser.tsx
> +import { TextField, Grid, ListItem, ListItemSecondaryAction, IconButton, Typography } from "@material-ui/core"
tương tự page Login

2021-07-19 07:08 UTC, hoaikthai commented on src/pages/UpdateUser.tsx
> +const UpdateUserInformationCardTextField = styled(TextField)`
```suggestion
const CustomTextField = styled(TextField)`
```

2021-07-19 07:08 UTC, hoaikthai commented on src/pages/UpdateUser.tsx
> +  const handleUpdateName = () => {
sao ko tạo form update hết luôn mà update từng field vậy e?

2021-07-19 07:08 UTC, hoaikthai commented on src/services/api/createApiClient.ts
> +function getLocalToken() {
bỏ

2021-07-19 07:08 UTC, hoaikthai commented on src/services/api/createApiClient.ts
> +    let token = getLocalToken()
```suggestion
    const token = localStorage.getItem("token")
```

2021-07-19 07:08 UTC, hoaikthai commented on src/services/api/createApiClient.ts
> +      const status = error.response ? error.response.status : null
e xử lý gì đây? khi nào mà lại quay về login?

2021-07-19 07:08 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +      return err
mặc định ko return gì, khi nào cần xử lý gì đặc biệt mới return, tương tự các hàm dưới

2021-07-19 08:24 UTC, Linhnef commented on src/services/api/createApiClient.ts
> +      const status = error.response ? error.response.status : null
dạ để em bỏ

2021-07-19 08:24 UTC, Linhnef commented on src/services/api/createApiClient.ts
> +      const status = error.response ? error.response.status : null
em định là bắt lỗi token hết hạn

2021-07-19 08:26 UTC, hoaikthai commented on src/services/api/createApiClient.ts
> +      const status = error.response ? error.response.status : null
ừ xử lý cái đó ở chỗ khác, chỗ này mình xử lý gọi API, ko liên quan gì

2021-07-19 09:32 UTC, Linhnef commented on src/pages/Login.tsx
> +  useEffect(() => {
chỗ này bỏ useEffect luôn hả anh

2021-07-19 09:32 UTC, Linhnef commented on src/pages/Login.tsx
> +  useEffect(() => {
@hoaikthai

2021-07-19 09:34 UTC, hoaikthai commented on src/pages/Login.tsx
> +  useEffect(() => {
mình nên tránh dùng useEffect khi có thể

2021-07-19 12:11 UTC, Linhnef commented on src/pages/Login.tsx
> +  useEffect(() => {
cái hàm useAsync nó nhận dữ liệu rồi nhưng nó bị deley nó k kịp tuyền xuống để setToken thì sử lí sao vậy anh mình lại dùng async function chỗ này hả anh @hoaikthai 

 const login = useAsync<LoginResponse | undefined | null, LoginRequest>(api.login)

  const handleLogin = (email: string, password: string) => {
    const result = login.run({ email: email, password: password })
    if (!result) return
    if (login.data) {
      setToken(login.data.token)
      setUser(login.data.user)
      history.replace("/")
    }
  }

2021-07-19 13:42 UTC, hoaikthai commented on src/pages/Login.tsx
> +  useEffect(() => {
login.run là 1 hàm async nên e có thể await để lấy kq đc 🙂

2021-07-20 02:16 UTC, hoaikthai requested changes

2021-07-20 02:16 UTC, hoaikthai commented on src/contexts/managerUIstateContext.tsx
> +export const ManagerUIstateContext = React.createContext<{ isCloseSodeMenu: boolean; change: () => void }>({
e cần context này để làm gì nhỉ? Việc sidebar đóng mở thì handle chỗ sidebar thôi chứ

2021-07-20 02:16 UTC, hoaikthai commented on src/pages/Register.tsx
> +  let formValid = false
validate form = 1 hàm, ko dùng biến let

2021-07-20 02:16 UTC, hoaikthai commented on src/pages/Login.tsx
> +  let formValid = false
validate form = 1 hàm, ko dùng biến let

2021-07-20 02:16 UTC, hoaikthai commented on src/services/api/createApiClient.ts
> +    const token = getLocalToken()
```suggestion
    const token = localStorage.getItem("token")
```

2021-07-20 02:51 UTC, Linhnef commented on src/contexts/managerUIstateContext.tsx
> +export const ManagerUIstateContext = React.createContext<{ isCloseSodeMenu: boolean; change: () => void }>({
dạ ví dụ mình làm cái trang kiểu khi thay đổi một cái thì có 4 5 thaành phần thay đổi thì mình nên viết context không anh

2021-07-20 02:52 UTC, Linhnef commented on src/contexts/managerUIstateContext.tsx
> +export const ManagerUIstateContext = React.createContext<{ isCloseSodeMenu: boolean; change: () => void }>({
hay context chỉ để quản lí dữ liệu thôi anh

2021-07-20 03:01 UTC, hoaikthai commented on src/contexts/managerUIstateContext.tsx
> +export const ManagerUIstateContext = React.createContext<{ isCloseSodeMenu: boolean; change: () => void }>({
nó có thể như e nói, nhưng mà trong trường hợp hiện tại thì có gì mà phải tạo context?

2021-07-21 04:21 UTC, hoaikthai requested changes

2021-07-21 04:21 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +      console.log(res.data.success)
bỏ console.log

2021-07-21 04:21 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +      console.log(res.data.success)
bỏ console.log

2021-07-21 04:21 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +    getAllTask: getAllTask(api),
```suggestion
    getAllTasks: getAllTasks(api),
```

2021-07-21 04:21 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +    getAllTask: getAllTask(api),
getAllTask, getTaskByCompleted, getTaskByPagnigation cơ bản chỉ là 1 API, chỉ khác params thôi, e gộp lại đi

2021-07-21 04:21 UTC, hoaikthai commented on src/pages/UpdateUser.tsx
> +    const result = await updateUser.run({ name: name, age, email })
e handle result trong `updateUser` luôn

2021-07-21 04:21 UTC, hoaikthai commented on src/pages/Logout.tsx
> +export const Logout = () => {
```suggestion
export const LogoutButton = () => {
```

2021-07-21 04:21 UTC, hoaikthai commented on src/pages/Logout.tsx
> +export const Logout = () => {
đổi lại tên file luôn

2021-07-21 04:21 UTC, hoaikthai commented on src/pages/Login.tsx
> +    if (!passwordInputHasError && !emailInputHasError) setFormValid(true)
```suggestion
    setFormValid(!passwordInputHasError && !emailInputHasError)
```

2021-07-21 04:21 UTC, hoaikthai commented on src/pages/Register.tsx
> +    if (!passwordInputHasError && !emailInputHasError && !ageInputHasError && !nameInputHasError) setFormValid(true)
```suggestion
    const isFormValid = !passwordInputHasError && !emailInputHasError && !ageInputHasError && !nameInputHasError
    setFormValid(isFormValid)
```

2021-07-21 04:21 UTC, hoaikthai commented on src/pages/Register.tsx
> +    if (!passwordInputHasError && !emailInputHasError && !ageInputHasError && !nameInputHasError) setFormValid(true)
cái đống này lặp code hơi nhiều nhé, nhưng mà mình sẽ giải quyết sau

2021-07-21 05:26 UTC, Linhnef commented on src/services/api/createAppApiClient.ts
> +    getAllTask: getAllTask(api),
cái này em update lại ở branch sau ở nha anh @hoaikthai

2021-07-22 03:08 UTC, hoaikthai requested changes

2021-07-22 03:08 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +      return null
return null thì khỏi cần return cũng đc, tương tự mấy cái dưới

2021-07-22 03:08 UTC, hoaikthai commented on src/pages/UpdateUser.tsx
> +    if (!data) return
bỏ logic handle update này vào `updateUser` async hook luôn
onClick chỉ cần để () => updateUser.run({name, age, email})

2021-07-22 03:08 UTC, hoaikthai commented on src/pages/Register.tsx
> +    const result = await register.run({
bỏ logic handle signUp này vào `register` async hook luôn
onClick chỉ cần để 
```ts
onClick={() => register.run({name: username, email, password, age,})}
```

2021-07-22 03:08 UTC, hoaikthai commented on src/pages/LogoutButton.tsx
> +    const result = await logout.run()
mang logic bỏ vào logout hook

2021-07-22 03:08 UTC, hoaikthai commented on src/pages/Login.tsx
> +    const result = await login.run({ email: email, password: password })
bỏ logic login vào login async hook

2021-07-22 04:21 UTC, Linhnef commented on src/pages/UpdateUser.tsx
> +    if (!data) return
Là bỏ hàm handleUpdate vào useAsync như này phải không anh. 

  const updateUser = useAsync<void, UpdateCurrentUserRequest>(async (updateUserRequest: 
        UpdateCurrentUserRequest) => {
              const response = await api.updateCurrentUser(updateUserRequest)
              if (!response) return
              setUser(response.data)
              history.replace("/")
       })

Là sau này mọi sử lý mà bất đồng bộ mình đề bỏ vào use async hết đúng không anh.

2021-07-22 04:53 UTC, hoaikthai commented on src/pages/UpdateUser.tsx
> +    if (!data) return
ko hẳn, nếu như mình ko quan tâm tới loading, error hay result của function async đó thì không cần dùng

2021-07-23 03:47 UTC, hoaikthai requested changes

2021-07-23 03:47 UTC, hoaikthai commented on src/hooks/useInput.ts
> +  return { value: value, isValueValid: isValueValid, hasError: hasError, valueChangeHanlder, inputBlurHandler, reset }
tại sao value, isValueValid, hasError e ko làm như valueChangeHanlder, inputBlurHandler, reset?
```suggestion
  return { value, isValueValid, hasError, valueChangeHanlder, inputBlurHandler, reset }
```

2021-07-23 03:47 UTC, hoaikthai commented on src/pages/LogoutButton.tsx
> +import { AuthenticationContext } from "../contexts/authenticationContext"
component này đâu phải là page đâu hè? sao lại để trong src/pages?

2021-07-23 03:53 UTC, Linhnef commented on src/pages/LogoutButton.tsx
> +import { AuthenticationContext } from "../contexts/authenticationContext"
dạ em tưởng là không được bỏ mấy cái mà có liên quan đến sử lí api bên trong component.

2021-07-23 03:54 UTC, hoaikthai commented on src/pages/LogoutButton.tsx
> +import { AuthenticationContext } from "../contexts/authenticationContext"
nếu cần thì bỏ bình thường chứ

2021-07-26 02:48 UTC, merged