Upload image
Linhnef/todo-list pull request #17
Opened 2021-08-24 09:39 UTC by Linhnef

2021-08-24 10:06 UTC, hoaikthai requested changes

2021-08-24 10:06 UTC, hoaikthai commented on package.json
> +    "node": "10.x",
cuối cùng là 10 hay 14 vậy e

2021-08-24 10:06 UTC, hoaikthai commented on src/layouts/MainLayout.tsx
> +  background-image: url("https://br-art.vn/wp-content/uploads/2017/07/background-phong-canh-45.jpg");
gán link này vào 1 biến rồi set vào đây

2021-08-24 10:06 UTC, hoaikthai commented on src/contexts/taskContext.tsx
> +import { useEffect } from "react"
ko dùng sao import?

2021-08-24 10:06 UTC, hoaikthai commented on src/pages/UpdateUser.tsx
> +    const file = event.currentTarget.files as unknown as File[]
```suggestion
    const files = event.currentTarget.files as unknown as File[]
```
số nhiều thì để biến dạng plural đi e
event.currentTarget.files ban đầu nó là type gì mà e phải cast vậy

2021-08-24 10:06 UTC, hoaikthai commented on src/pages/UpdateUser.tsx
> +    if (!response) return
dòng này để làm gì?

2021-08-24 10:06 UTC, hoaikthai commented on src/pages/UpdateUser.tsx
> +              <ButtonOutlined color="primary" onClick={() => handleUpdate()}>
```suggestion
              <ButtonOutlined color="primary" onClick={handleUpdate}>
```

2021-08-24 10:06 UTC, hoaikthai commented on src/pages/UpdateUser.tsx
> +  & .MuiAvatar-root {
ủa style avatar sao lại ở đây?

2021-08-24 10:06 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +      console.log(res.data.data)
bỏ

2021-08-24 12:38 UTC, Linhnef commented on src/pages/UpdateUser.tsx
> +    const file = event.currentTarget.files as unknown as File[]
dạ nó ghi là trả về một FileList  | null em tưởng nó là object nên em cast em sửa rồi ạ.

2021-08-24 12:54 UTC, Linhnef commented on package.json
> +    "node": "10.x",
dạ cái này em research  khuyên dùng bản 14x mà máy em cài bản 10x nên em đổi lại

2021-09-06 08:30 UTC, hoaikthai requested changes

2021-09-06 08:30 UTC, hoaikthai commented on src/App.tsx
> +            <TaskContextProvider>
bọc context trong page, ở ngoài này chỉ có route thôi

2021-09-06 08:30 UTC, hoaikthai commented on src/layouts/MainLayout.tsx
> +  height: 100vh;
```suggestion
  height: 100%;
```

2021-09-06 08:30 UTC, hoaikthai commented on src/layouts/MainLayout.tsx
> +  height: 100vh;
e set cứng height vậy lỡ content tràn ra ngoài thì sao

2021-09-06 09:12 UTC, hoaikthai commented
e có thể fix hết trong 1 commit, ko cần phải chia ra vậy

2021-09-06 09:17 UTC, merged