Get user image
Linhnef/todo-list pull request #18
Opened 2021-09-06 11:05 UTC by Linhnef

2021-09-06 11:42 UTC, hoaikthai requested changes

2021-09-06 11:42 UTC, hoaikthai commented on src/pages/Home.tsx
> +              <Avatar src={userAvatar ? userAvatar : ""} />
nếu ko có avatar thì avatar mặc định kiểu chứa chữ cái đầu của firstName vs lastName của user

2021-09-06 13:37 UTC, hoaikthai requested changes

2021-09-06 13:37 UTC, hoaikthai commented on src/pages/Home.tsx
> +              {userAvatar ? <Avatar src={userAvatar} /> : <Avatar>{generaDefaultAvatar()}</Avatar>}
rồi e định chỗ nào hiện avatar là phải như này à

- [ ] tạo component UserAvatar

2021-09-06 13:37 UTC, hoaikthai commented on src/pages/Home.tsx
> +  const generaDefaultAvatar = () => {
hàm return về chữ cái đầu của 1 chuỗi e đặt tên vậy có chuẩn ko?

- [ ] rename thành getAbbreviatedString
- [ ] tách ra thành 1 helper, input nhận 1 string

2021-09-06 13:37 UTC, hoaikthai commented on src/pages/Home.tsx
> +    if (!user) return "?".toUpperCase()
? upcase lên ra gì e?

2021-09-06 13:37 UTC, hoaikthai commented on src/pages/Home.tsx
> +    if (nameArray?.length === 1) return nameArray[0][0].toUpperCase()
xử lý cồng kềnh

```ts
return user?.name.split(" ").map((word) => word[0]).join("") ?? "?"
```

2021-09-06 13:37 UTC, hoaikthai commented on src/pages/Home.tsx
> +    if (nameArray?.length === 1) return nameArray[0][0].toUpperCase()
xử lý hơi cồng kềnh

```ts
return user?.name.split(" ").map(word => word[0].toUpperCase()).join("") ?? "?"
```

2021-09-06 15:23 UTC, hoaikthai commented on src/components/UserAvatar.tsx
> +function UserAvatar() {
sao giờ lại là function bt rồi?
tại sao e lấy từ context mà ko truyền prop vào component này?

2021-09-06 15:25 UTC, hoaikthai commented on src/helpers/getAbbreviatedString.ts
> +          .filter((word, index) => index === 0 || index === data.length)
index của word lqan gì tới độ dài chuỗi???
e muốn input output của hàm này như nào list cho a vài case thử

2021-09-06 15:26 UTC, Linhnef commented on src/helpers/getAbbreviatedString.ts
> +          .filter((word, index) => index === 0 || index === data.length)
dạ ý là em muốn vd tên có 3 chữ thì lấy 2 chữ đầu và cuối

2021-09-06 15:28 UTC, hoaikthai commented on src/helpers/getAbbreviatedString.ts
> +          .filter((word, index) => index === 0 || index === data.length)
vậy tên hàm này lại sai rồi, mà e filter cũng sai nốt

2021-09-06 15:29 UTC, hoaikthai commented on src/helpers/getAbbreviatedString.ts
> +          .filter((word, index) => index === 0 || index === data.length)
e thử thêm 1 file .spec.ts rồi viết test cho hàm này xem

2021-09-06 15:54 UTC, Linhnef commented on src/components/UserAvatar.tsx
> +function UserAvatar() {
dạ do em thấy k có checked để check em mới fix lại ạ

2021-09-06 15:55 UTC, Linhnef commented on src/helpers/getAbbreviatedString.ts
> +          .filter((word, index) => index === 0 || index === data.length)
dạ chỗ này em quên thêm split(" ")

2021-09-06 16:06 UTC, hoaikthai commented on src/components/UserAvatar.tsx
> +    console.log(getAbbreviatedString(props.name))
?

2021-09-06 16:19 UTC, Linhnef commented on src/components/UserAvatar.tsx
> +    console.log(getAbbreviatedString(props.name))
dạ em quên xóa

2021-09-07 02:26 UTC, hoaikthai commented on src/components/UserAvatar.tsx
> +interface UserAvatarProps {
cái này a hỏi thôi, sao e dùng interface mà ko dùng type?

2021-09-07 02:26 UTC, hoaikthai commented on src/components/UserAvatar.tsx
> +    <> {props.userAvatar ? <Avatar src={props.userAvatar} /> : <Avatar>{getAbbreviatedString(props.name)}</Avatar>}</>
<> ko cần thiết

2021-09-07 02:27 UTC, hoaikthai commented on src/helpers/getAbbreviatedString.spec.ts
> +import { getAbbreviatedString } from "./getAbbreviatedString"
coi lại chính tả/ngữ pháp mấy câu e viết

2021-09-07 02:42 UTC, Linhnef commented on src/components/UserAvatar.tsx
> +interface UserAvatarProps {
dạ do lúc đầu em học với đứa bạn thường viết là interface nên em quen . em sửa rồi ạ

2021-09-07 02:44 UTC, hoaikthai commented on src/components/UserAvatar.tsx
> +interface UserAvatarProps {
a có bắt e sửa đâu??? a hỏi thôi mà :D

2021-09-07 02:46 UTC, hoaikthai commented on src/helpers/getAbbreviatedString.spec.ts
> +import { getAbbreviatedString } from "./getAbbreviatedString"
chưa resolved

2021-09-07 03:01 UTC, Linhnef commented on src/components/UserAvatar.tsx
> +interface UserAvatarProps {
dạ

2021-09-07 03:03 UTC, hoaikthai commented on src/helpers/getAbbreviatedString.spec.ts
> +import { getAbbreviatedString } from "./getAbbreviatedString"
chưa resolved

2021-09-07 03:15 UTC, Linhnef commented on src/helpers/getAbbreviatedString.spec.ts
> +import { getAbbreviatedString } from "./getAbbreviatedString"
dạ em update lại thấy bên beanch có code rồi mà soa bên này vẫn không có.
```import { getAbbreviatedString } from "./getAbbreviatedString"

describe("Get Abbreviated String", () => {
  it("it should be return first and last word of string", () => {
    expect(getAbbreviatedString("Trần Dần")).toEqual("TD")
    expect(getAbbreviatedString("Nguyễn Bảo Linh")).toEqual("LB")
    expect(getAbbreviatedString("Phạm Thị Mỹ Nhân")).toEqual("PN")
  })
  it("it should be return the firt character  of word", () => {
    expect(getAbbreviatedString("Linh")).toEqual("L")
  })
})
```

2021-09-07 03:28 UTC, hoaikthai commented on src/helpers/getAbbreviatedString.spec.ts
> +import { getAbbreviatedString } from "./getAbbreviatedString"
a vẫn thấy còn sai thôi

2021-09-07 03:47 UTC, Linhnef commented on src/helpers/getAbbreviatedString.spec.ts
> +import { getAbbreviatedString } from "./getAbbreviatedString"
dạ em sai chính tả :(

2021-09-07 03:53 UTC, hoaikthai commented on src/helpers/getAbbreviatedString.spec.ts
> +import { getAbbreviatedString } from "./getAbbreviatedString"
ngữ pháp nữa

2021-09-07 04:07 UTC, Linhnef commented on src/helpers/getAbbreviatedString.spec.ts
> +import { getAbbreviatedString } from "./getAbbreviatedString"
dạ e vừa sửa lại

2021-09-08 16:21 UTC, hoaikthai commented on src/helpers/getAbbreviatedString.spec.ts
> +  it("it should be return first character of the first word and also of the last word", () => {
```suggestion
  it("should return the first character of the first and the last words", () => {
```

2021-09-08 16:22 UTC, hoaikthai commented on src/helpers/getAbbreviatedString.spec.ts
> +  it("it should be return the first character of word", () => {
```suggestion
  it("should return the first character of the one-word string", () => {
```

2021-09-09 03:12 UTC, merged