Get by pagnigation
Linhnef/todo-list pull request #8
Opened 2021-08-03 03:17 UTC by Linhnef

2021-08-03 14:16 UTC, hoaikthai requested changes

2021-08-03 14:16 UTC, hoaikthai commented on src/pages/Tasks.tsx
> +                  onClick={() => {
tạo hàm riêng, ko để như này

2021-08-03 14:16 UTC, hoaikthai commented on src/pages/Tasks.tsx
> +                  onClick={() => {
tạo hàm riêng hoặc dùng chung hàm ở trên

2021-08-04 15:11 UTC, hoaikthai commented on src/pages/Tasks.tsx
> +  const firstPage = () => {
tên hàm nên là động từ e

2021-08-04 15:47 UTC, hoaikthai commented on src/pages/Tasks.tsx
> +  const firstPage = () => {
2 hàm ở dưới nữa 😉

2021-08-04 15:51 UTC, Linhnef commented on src/pages/Tasks.tsx
> +  const firstPage = () => {
anh ơi em thấy materrialUI người ta thường dùng mấy cái như makesStyle rồi có hắn có máy cái class sẵn ở trong đó vậy mỗi khi css mình phải tra class của nó hả anh

2021-08-04 15:54 UTC, hoaikthai commented on src/pages/Tasks.tsx
> +  const firstPage = () => {
mình dùng styled-component rồi nên ko cần tới makeStyle của nó, e cần custom component gì cũng nó bọc lại = styled component đc mà, còn nếu để style component bên trong nữa thì ínpect coi class nó r custom thôi

2021-08-04 15:57 UTC, Linhnef commented on src/pages/Tasks.tsx
> +  const firstPage = () => {
dạa

2021-08-07 06:28 UTC, hoaikthai requested changes

2021-08-07 06:28 UTC, hoaikthai commented on src/pages/Tasks.tsx
> +  const [page, setPage] = useState(0)
page bắt đầu từ 1

2021-08-07 06:28 UTC, hoaikthai commented on src/pages/Tasks.tsx
> +  const getFirstPage = () => {
khi chuyển trang thì set query params trên url: `?page=<page>`

2021-08-07 06:28 UTC, hoaikthai commented on src/pages/Tasks.tsx
> +    setPage(page - 1)
ko có giới hạn dưới à e, về -n vẫn đc à

2021-08-07 16:19 UTC, hoaikthai commented on src/pages/Tasks.tsx
> +    history.push(`/task?page=${page}`)
nếu như trên thanh url a tự nhập query page thì list của e có tự đổi page theo ko?

2021-08-07 16:50 UTC, Linhnef commented on src/pages/Tasks.tsx
> +    history.push(`/task?page=${page}`)
em vừa update dùng useEfect như vậy đúng k anh

2021-08-08 03:13 UTC, hoaikthai commented on src/pages/Tasks.tsx
> +    history.push(`/task?page=${page}`)
e qua page thì url có đổi theo ko?

2021-08-08 05:54 UTC, hoaikthai commented on src/pages/Tasks.tsx
> +    history.push(`/task?page=${page}`)
e nên cài thêm `query-string` để thao túng query nhé, viết hook useQuery trả về [query, patchQuery] thì tốt
- query get object trên query params hiện tại
- patchQuery để patch query name cần sửa

2021-08-08 12:21 UTC, hoaikthai requested changes

2021-08-08 12:21 UTC, hoaikthai commented on src/hooks/useQuery.ts
> +import * as queryString from "query-string"
```suggestion
import { parse, stringify } from "query-string"
```

2021-08-08 12:21 UTC, hoaikthai commented on src/hooks/useQuery.ts
> +  const queryUrl = window.location.search
```suggestion
  const queryString = useLocation().search
```

2021-08-08 12:21 UTC, hoaikthai commented on src/hooks/useQuery.ts
> +const useQuery = () => {
```suggestion
export const useQuery = <TQuery>(initialQuery: TQuery) => {
```

2021-08-08 12:21 UTC, hoaikthai commented on src/hooks/useQuery.ts
> +  useEffect(() => {
có cách nào ko dùng useEffect ko?

2021-08-08 12:21 UTC, hoaikthai commented on src/hooks/useQuery.ts
> +    history.push(window.location.pathname + `?${stringify(objs)}`)
```suggestion
    history.push({search: stringify(updatedQuery)})
```

2021-08-08 14:21 UTC, hoaikthai commented on src/pages/Tasks.tsx
> -import {
format file này bị gì vậy e

2021-08-08 14:36 UTC, Linhnef commented on src/pages/Tasks.tsx
> -import {
dạ không biết sao em cứ bị conflict miết :(

2021-08-09 02:37 UTC, hoaikthai commented on src/hooks/useQuery.ts
> +  const [query, setQuery] = useState<TQuery | any>(initialQuery)
sao lại type any nhỉ?

2021-08-09 02:37 UTC, hoaikthai commented on src/hooks/useQuery.ts
> +  const patchQuery = (obj: TQuery) => {
```suggestion
  const patchQuery = (updatedQuery: TQuery) => {
```

2021-08-09 03:30 UTC, Linhnef commented on src/hooks/useQuery.ts
> +  const [query, setQuery] = useState<TQuery | any>(initialQuery)
import { parse } from "query-string"
useEffect(() => {
        const queryParams = parse(queryString)
        setQuery(queryParams)
}, [queryString])

dạ do em đang  convert queryParams về kiểu TQuery mà chưa được

2021-08-09 06:23 UTC, hoaikthai commented on src/hooks/useQuery.ts
> +  useEffect(() => {
ko có cách nào bỏ useEffect à e?

2021-08-09 07:37 UTC, Linhnef commented on src/hooks/useQuery.ts
> +  useEffect(() => {
dạ em mới update lại

2021-08-10 03:25 UTC, hoaikthai commented on src/hooks/useQuery.ts
> +    setQuery(queryParams)
e để ý mình có bao giờ gọi setState ở ngoài như này bao giờ chưa, mình chỉ gọi ở trong hàm xử lý hoặc trong useEffect

quay lại hỏi, tại sao e cần phải tạo state cho query, mình thay đổi nó khi nào?

2021-08-10 06:19 UTC, Linhnef commented on src/hooks/useQuery.ts
> +    setQuery(queryParams)
dạ lúc trước e có viết : 

```
const query = parse(queryString) as unknown as TQuery
```
nhưng em thấy như vậy thì k initial được query nên em dùng useState
dạ em mớ sửa lại thành : 


```
  const query = parse(queryString) as unknown as TQuery ? parse(queryString) as unknown as TQuery  : initialQuery 
```

2021-08-11 03:18 UTC, hoaikthai commented on src/hooks/useQuery.ts
> +  const query = parse(queryString) as unknown as TQuery ? parse(queryString) as unknown as TQuery  : initialQuery
```suggestion
  const query = { initialQuery, ...parse(queryString) }
```
vậy đc ko

2021-08-11 03:28 UTC, Linhnef commented on src/hooks/useQuery.ts
> +  const query = parse(queryString) as unknown as TQuery ? parse(queryString) as unknown as TQuery  : initialQuery
dạ

2021-08-11 03:40 UTC, hoaikthai commented on src/pages/Tasks.tsx
> +    setPage(1)
ko cần page state nữa, patchQuery cho page là đủ

2021-08-11 04:12 UTC, Linhnef commented on src/pages/Tasks.tsx
> +    setPage(1)
dạ

2021-08-11 04:31 UTC, merged